/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login_window (void);
GtkWidget* create_Admin_window (void);
GtkWidget* create_ajouter_infirmier_window (void);
GtkWidget* create_ajouter_technicien_window (void);
GtkWidget* create_ajouter_aide_soignant_window (void);
GtkWidget* create_technicien_window (void);
GtkWidget* create_edit_window (void);
GtkWidget* create_ajout_camera (void);
GtkWidget* create_ajout_bracelet (void);
GtkWidget* create_edit_camera_window (void);
GtkWidget* create_edit_bracelet_window (void);
GtkWidget* create_ajouter_medecin_window (void);
GtkWidget* create_ajout_succes_window (void);
GtkWidget* create_edit_infirmier_window (void);
GtkWidget* create_edit_technicien_window (void);
GtkWidget* create_edit_as_window (void);
GtkWidget* create_ajouter_persoag (void);
GtkWidget* create_Espace_medecin (void);
GtkWidget* create_espace_as (void);
GtkWidget* create_Espace_infirmier (void);
GtkWidget* create_ajout_mat_window (void);
GtkWidget* create_window1 (void);
GtkWidget* create_cam_window (void);
GtkWidget* create_window2 (void);
